### ISSUE TITLE
Checklist de passage de versions

### ISSUE THREAD

**Issue by Brancieq-Paul** [HB-Modding-Crew/Herobrine.fr-Optimized#99]
### Tâche interne

Template de checklist pour passer d'une version à une autre. Elle doit être répétée pour chaque version, et peut varier d'une version à l'autre:

Tâches avant exportation:

- [ ] Changer le nom de la version dans l'affichage du main menu
- [ ] S'assurer que les options changées individuellement sont bien définies
- [ ] S'assurer que les options changées individuellement sont bien changées dans les options par défaut
- [ ] Vérifier que les options des mods ajoutés ont bien été définies par défaut

Tâches après exportation:

- [ ] Bien s'assurer que les layouts désactivés ont bien été mis dans l'exportation de l'instance CurseForge
- [ ] De manière générale, tester les options qui ont été changées dans l'ensemble des launchers

**Comment by Brancieq-Paul** [comment]
### 2.0.0-alpha.7

Tâches avant exportation:

- [ ] Changer le nom de la version dans l'affichage du main menu
- [ ] S'assurer que les options changées individuellement sont bien définies
- [ ] S'assurer que les options changées individuellement sont bien changées dans les options par défaut
- [ ] Vérifier que les options des mods ajoutés ont bien été définies par défaut

Tâches après exportation:

- [ ] Bien s'assurer que les layouts désactivés ont bien été mis dans l'exportation de l'instance CurseForge
- [ ] De manière générale, tester les options qui ont été changées dans l'ensemble des launchers

**Comment by Brancieq-Paul** [comment]
Seulement un template, close et pin.
